package com.hideonshroud.assigement_4

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {

   private lateinit var  recyclerView: RecyclerView
   private lateinit var data: ArrayList<Data>
   private lateinit var dataAdapter: Adapter

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        recyclerView = findViewById(R.id.recyclerView)
        recyclerView.setHasFixedSize(true)
        recyclerView.layoutManager = LinearLayoutManager(this)

        data = ArrayList()

        data.add(Data("HideOnShroud", "https://avatars.githubusercontent.com/u/93008528?v=4","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget lectus auctor, convallis sapien non, fringilla ligula. Sed porttitor orci id pharetra auctor. Vestibulum rutrum purus vitae nisi ornare, in aliquam leo fringilla. Aliquam in quam convallis, auctor odio sit amet, pulvinar sem. Vivamus quis diam odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vitae consectetur massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit."))
        data.add(Data("BeefyBento", "https://miro.medium.com/v2/resize:fit:1200/1*HmtkzxNYchDkG3n9IIbCZg.png","Nullam scelerisque diam justo, eget vestibulum orci volutpat id. Aenean id dapibus erat. Duis vel mi mauris. Mauris consequat sollicitudin orci, vitae faucibus enim semper eu. Pellentesque nisl libero, interdum at hendrerit a, volutpat eu justo. Ut felis metus, commodo nec venenatis quis, pharetra nec sem. Nullam eros enim, accumsan vel commodo non, luctus ac risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eleifend interdum ullamcorper. In lacinia, dui eget suscipit tincidunt, mi sapien tincidunt erat, at malesuada nibh dui vulputate dolor. Nunc a enim at ex sollicitudin dictum quis id quam. Nam et nunc at justo interdum maximus."))
        data.add(Data("CloudFlare", "https://static-00.iconduck.com/assets.00/cloudflare-icon-2048x2048-wks6nchu.png","Integer eget est odio. Praesent id mauris blandit, condimentum magna sed, aliquet dolor. Aliquam facilisis mauris ac dictum cursus. Aliquam eget rutrum orci. Fusce mauris ante, egestas quis rhoncus a, euismod nec dolor. Quisque justo augue, feugiat quis mattis sit amet, elementum ut libero. Cras vitae turpis quis libero cursus euismod. Quisque id nibh vulputate, dapibus massa eleifend, luctus turpis. Suspendisse laoreet facilisis viverra. Aliquam condimentum molestie magna at sagittis. Praesent scelerisque odio quam, nec condimentum libero luctus et. Morbi vitae fringilla metus, vel laoreet ex. Duis eleifend nisi vitae ex dignissim auctor. Sed ex elit, accumsan in sagittis eget, lobortis vitae lacus."))
        data.add(Data("Deonica", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4BMPedbNFIjaKo63jElUNB5VUSA3KXDbDjg&usqp=CAU","Etiam faucibus, diam id porttitor aliquam, orci dolor faucibus ante, a faucibus felis quam nec ipsum. Maecenas aliquet purus eget risus hendrerit, ac gravida ligula vestibulum. Suspendisse tellus neque, dapibus ac tincidunt nec, fermentum quis magna. Cras lacinia viverra mauris nec pretium. Curabitur ultricies magna nec nisl ornare, a auctor nibh lobortis. Ut at euismod sapien. Curabitur nisl turpis, rhoncus a nunc eu, lacinia rhoncus erat. Ut sed pretium orci. Nam nulla nisi, mattis sit amet enim a, condimentum sollicitudin quam. Nulla facilisi. Pellentesque non molestie lorem. Praesent nec dui at enim gravida sodales. Mauris sit amet ex condimentum, rhoncus lorem a, egestas dui."))
        data.add(Data("HideOnShroud", "https://avatars.githubusercontent.com/u/93008528?v=4","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget lectus auctor, convallis sapien non, fringilla ligula. Sed porttitor orci id pharetra auctor. Vestibulum rutrum purus vitae nisi ornare, in aliquam leo fringilla. Aliquam in quam convallis, auctor odio sit amet, pulvinar sem. Vivamus quis diam odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vitae consectetur massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit."))
        data.add(Data("BeefyBento", "https://miro.medium.com/v2/resize:fit:1200/1*HmtkzxNYchDkG3n9IIbCZg.png","Nullam scelerisque diam justo, eget vestibulum orci volutpat id. Aenean id dapibus erat. Duis vel mi mauris. Mauris consequat sollicitudin orci, vitae faucibus enim semper eu. Pellentesque nisl libero, interdum at hendrerit a, volutpat eu justo. Ut felis metus, commodo nec venenatis quis, pharetra nec sem. Nullam eros enim, accumsan vel commodo non, luctus ac risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eleifend interdum ullamcorper. In lacinia, dui eget suscipit tincidunt, mi sapien tincidunt erat, at malesuada nibh dui vulputate dolor. Nunc a enim at ex sollicitudin dictum quis id quam. Nam et nunc at justo interdum maximus."))
        data.add(Data("CloudFlare", "https://static-00.iconduck.com/assets.00/cloudflare-icon-2048x2048-wks6nchu.png","Integer eget est odio. Praesent id mauris blandit, condimentum magna sed, aliquet dolor. Aliquam facilisis mauris ac dictum cursus. Aliquam eget rutrum orci. Fusce mauris ante, egestas quis rhoncus a, euismod nec dolor. Quisque justo augue, feugiat quis mattis sit amet, elementum ut libero. Cras vitae turpis quis libero cursus euismod. Quisque id nibh vulputate, dapibus massa eleifend, luctus turpis. Suspendisse laoreet facilisis viverra. Aliquam condimentum molestie magna at sagittis. Praesent scelerisque odio quam, nec condimentum libero luctus et. Morbi vitae fringilla metus, vel laoreet ex. Duis eleifend nisi vitae ex dignissim auctor. Sed ex elit, accumsan in sagittis eget, lobortis vitae lacus."))
        data.add(Data("Deonica", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4BMPedbNFIjaKo63jElUNB5VUSA3KXDbDjg&usqp=CAU","Etiam faucibus, diam id porttitor aliquam, orci dolor faucibus ante, a faucibus felis quam nec ipsum. Maecenas aliquet purus eget risus hendrerit, ac gravida ligula vestibulum. Suspendisse tellus neque, dapibus ac tincidunt nec, fermentum quis magna. Cras lacinia viverra mauris nec pretium. Curabitur ultricies magna nec nisl ornare, a auctor nibh lobortis. Ut at euismod sapien. Curabitur nisl turpis, rhoncus a nunc eu, lacinia rhoncus erat. Ut sed pretium orci. Nam nulla nisi, mattis sit amet enim a, condimentum sollicitudin quam. Nulla facilisi. Pellentesque non molestie lorem. Praesent nec dui at enim gravida sodales. Mauris sit amet ex condimentum, rhoncus lorem a, egestas dui."))
        data.add(Data("HideOnShroud", "https://avatars.githubusercontent.com/u/93008528?v=4","Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget lectus auctor, convallis sapien non, fringilla ligula. Sed porttitor orci id pharetra auctor. Vestibulum rutrum purus vitae nisi ornare, in aliquam leo fringilla. Aliquam in quam convallis, auctor odio sit amet, pulvinar sem. Vivamus quis diam odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vitae consectetur massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit."))
        data.add(Data("BeefyBento", "https://miro.medium.com/v2/resize:fit:1200/1*HmtkzxNYchDkG3n9IIbCZg.png","Nullam scelerisque diam justo, eget vestibulum orci volutpat id. Aenean id dapibus erat. Duis vel mi mauris. Mauris consequat sollicitudin orci, vitae faucibus enim semper eu. Pellentesque nisl libero, interdum at hendrerit a, volutpat eu justo. Ut felis metus, commodo nec venenatis quis, pharetra nec sem. Nullam eros enim, accumsan vel commodo non, luctus ac risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eleifend interdum ullamcorper. In lacinia, dui eget suscipit tincidunt, mi sapien tincidunt erat, at malesuada nibh dui vulputate dolor. Nunc a enim at ex sollicitudin dictum quis id quam. Nam et nunc at justo interdum maximus."))
        data.add(Data("CloudFlare", "https://static-00.iconduck.com/assets.00/cloudflare-icon-2048x2048-wks6nchu.png","Integer eget est odio. Praesent id mauris blandit, condimentum magna sed, aliquet dolor. Aliquam facilisis mauris ac dictum cursus. Aliquam eget rutrum orci. Fusce mauris ante, egestas quis rhoncus a, euismod nec dolor. Quisque justo augue, feugiat quis mattis sit amet, elementum ut libero. Cras vitae turpis quis libero cursus euismod. Quisque id nibh vulputate, dapibus massa eleifend, luctus turpis. Suspendisse laoreet facilisis viverra. Aliquam condimentum molestie magna at sagittis. Praesent scelerisque odio quam, nec condimentum libero luctus et. Morbi vitae fringilla metus, vel laoreet ex. Duis eleifend nisi vitae ex dignissim auctor. Sed ex elit, accumsan in sagittis eget, lobortis vitae lacus."))
        data.add(Data("Deonica", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4BMPedbNFIjaKo63jElUNB5VUSA3KXDbDjg&usqp=CAU","Etiam faucibus, diam id porttitor aliquam, orci dolor faucibus ante, a faucibus felis quam nec ipsum. Maecenas aliquet purus eget risus hendrerit, ac gravida ligula vestibulum. Suspendisse tellus neque, dapibus ac tincidunt nec, fermentum quis magna. Cras lacinia viverra mauris nec pretium. Curabitur ultricies magna nec nisl ornare, a auctor nibh lobortis. Ut at euismod sapien. Curabitur nisl turpis, rhoncus a nunc eu, lacinia rhoncus erat. Ut sed pretium orci. Nam nulla nisi, mattis sit amet enim a, condimentum sollicitudin quam. Nulla facilisi. Pellentesque non molestie lorem. Praesent nec dui at enim gravida sodales. Mauris sit amet ex condimentum, rhoncus lorem a, egestas dui."))

        dataAdapter = Adapter(data)
        recyclerView.adapter = dataAdapter

        dataAdapter.onItemClick = {
            val intent = Intent(this, ItemActivity::class.java)
            intent.putExtra("NAME", it.userName)
            intent.putExtra("DESC", it.description)
            intent.putExtra("IMAGE", it.image)
            startActivity(intent)
        }
    }
}